[book]
authors = ["kunkka"]
language = "en"
multilingual = false
src = "src"
title = "Calendar"

[output.html]
additional-css = ["mermaid.css", "custom.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
