[book]
authors = ["kunkka"]
language = "en"
multilingual = false
src = "src"
title = "Calendar"

[output.html]
additional-css = ["mermaid.css", "custom.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
git-repository-url = "https://github.com/softtiny/docs.calendar"
git-repository-icon = "fa-github"

[output.html.print]
enable = false

[preprocessor.katex]
after = ["links"]
